---
version: 2
multicolumn: true
web-width: 700px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Figure_31/Figure_31.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/522596/articles/595019/master/file/figures/Figure_31/Figure_31.png"
    folder_url: "/users/522596/articles/595019/master/folder/figures/Figure_31"
