---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Figure_111/Figure_111.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/522596/articles/595019/master/file/figures/Figure_111/Figure_111.png"
